{"filteredValue":{"id":"generalInflationRateAmount2","value":0.020,"start":1,"end":1,"remarks":"2004"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.0424,"start":2,"end":2,"remarks":"2005"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.0664,"start":3,"end":3,"remarks":"2006"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.0915,"start":4,"end":4,"remarks":"2007"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.1323,"start":5,"end":5,"remarks":"2008"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.1426,"start":6,"end":6,"remarks":"2009"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.1662,"start":7,"end":7,"remarks":"2010"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.1980,"start":8,"end":8,"remarks":"2011"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.2246,"start":9,"end":9,"remarks":"2012"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.2400,"start":10,"end":10,"remarks":"2013"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.2424,"start":11,"end":11,"remarks":"2014"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.2424,"start":12,"end":12,"remarks":"2015"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.2451,"start":13,"end":13,"remarks":"2016"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.2668,"start":14,"end":14,"remarks":"2017"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.2881,"start":15,"end":15,"remarks":"2018"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.3032,"start":16,"end":16,"remarks":"2019"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.3104,"start":17,"end":17,"remarks":"2020"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.3382,"start":18,"end":18,"remarks":"2021"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.4415,"start":19,"end":19,"remarks":"2022"}}
{"filteredValue":{"id":"generalInflationRateAmount2","value":0.5035,"start":20,"end":20,"remarks":"2023"}}
{"filteredValue":{"id":"iRRAmount3","value":0.020,"start":1,"end":1,"remarks":"2004"}}
{"filteredValue":{"id":"iRRAmount3","value":0.0404,"start":2,"end":2,"remarks":"2005"}}
{"filteredValue":{"id":"iRRAmount3","value":0.0620,"start":3,"end":3,"remarks":"2006"}}
{"filteredValue":{"id":"iRRAmount3","value":0.0859,"start":4,"end":4,"remarks":"2007"}}
{"filteredValue":{"id":"iRRAmount3","value":0.1126,"start":5,"end":5,"remarks":"2008"}}
{"filteredValue":{"id":"iRRAmount3","value":0.1419,"start":6,"end":6,"remarks":"2009"}}
{"filteredValue":{"id":"iRRAmount3","value":0.1743,"start":7,"end":7,"remarks":"2010"}}
{"filteredValue":{"id":"iRRAmount3","value":0.2099,"start":8,"end":8,"remarks":"2011"}}
{"filteredValue":{"id":"iRRAmount3","value":0.2488,"start":9,"end":9,"remarks":"2012"}}
{"filteredValue":{"id":"iRRAmount3","value":0.2912,"start":10,"end":10,"remarks":"2013"}}
{"filteredValue":{"id":"iRRAmount3","value":0.3372,"start":11,"end":11,"remarks":"2014"}}
{"filteredValue":{"id":"iRRAmount3","value":0.3869,"start":12,"end":12,"remarks":"2015"}}
{"filteredValue":{"id":"iRRAmount3","value":0.4406,"start":13,"end":13,"remarks":"2016"}}
{"filteredValue":{"id":"iRRAmount3","value":0.4983,"start":14,"end":14,"remarks":"2017"}}
{"filteredValue":{"id":"iRRAmount3","value":0.5602,"start":15,"end":15,"remarks":"2018"}}
{"filteredValue":{"id":"iRRAmount3","value":0.6264,"start":16,"end":16,"remarks":"2019"}}
{"filteredValue":{"id":"iRRAmount3","value":0.6970,"start":17,"end":17,"remarks":"2020"}}
{"filteredValue":{"id":"iRRAmount3","value":0.7722,"start":18,"end":18,"remarks":"2021"}}
{"filteredValue":{"id":"iRRAmount3","value":0.8521,"start":19,"end":19,"remarks":"2022"}}
{"filteredValue":{"id":"iRRAmount3","value":0.9369,"start":20,"end":20,"remarks":"2023"}}

{"filteredValues":[{"id":"plantLifetimeAmount1","value":20,"remarks":""},{"id":"bECAmount1","value":200000,"remarks":""},{"id":"numberOfUnitsAmount1","value":30000,"remarks":""},{"id":"initialSellingPriceAmount1","value":2,"remarks":""},{"id":"totalOperatingCostPercentageAmount1","value":0.1,"remarks":""},{"id":"engineering_Procurement_and_Construction_EPC_BECAmount1","value":0,"remarks":""},{"id":"process_contingency_PC_BECAmount1","value":0.1,"remarks":""},{"id":"project_Contingency_PT_BEC_EPC_PCAmount1","value":0,"remarks":""},{"id":"use_direct_operating_expensesAmount1","value":"False","remarks":""},{"id":"depreciationMethodAmount2","value":"Straight-Line","remarks":""},{"id":"loanTypeAmount2","value":"simple","remarks":""},{"id":"interestTypeAmount2","value":"fixed","remarks":""},{"id":"generalInflationRateAmount2","value":0,"remarks":""},{"id":"interestProportionAmount2","value":0.5,"remarks":""},{"id":"principalProportionAmount2","value":0.5,"remarks":""},{"id":"loanPercentageAmount2","value":0.2,"remarks":""},{"id":"repaymentPercentageOfRevenueAmount2","value":0.1,"remarks":""},{"id":"numberofconstructionYearsAmount2","value":5,"remarks":""},{"id":"iRRAmount3","value":0.05,"remarks":""},{"id":"annualInterestRateAmount3","value":0.04,"remarks":""},{"id":"stateTaxRateAmount3","value":0.05,"remarks":""},{"id":"federalTaxRateAmount3","value":0.21,"remarks":""},{"id":"rawmaterialAmount3","value":10000,"remarks":""},{"id":"laborAmount3","value":24000,"remarks":""},{"id":"utilityAmount3","value":5000,"remarks":""},{"id":"maintenanceAmount3","value":2500,"remarks":""},{"id":"insuranceAmount3","value":500,"remarks":""},{"id":"gCAmount4","value":0,"remarks":""},{"id":"ammoniaAmount4","value":0,"remarks":""},{"id":"sulfuricAcidAmount4","value":0,"remarks":""},{"id":"fluorineAmount4","value":0,"remarks":""},{"id":"fluorsparTransportAmount4","value":0,"remarks":""},{"id":"naturalGasAmount4","value":0,"remarks":""},{"id":"electricityAmount4","value":0,"remarks":""},{"id":"processWaterAmount4","value":0,"remarks":""},{"id":"coolingWaterAmount4","value":0,"remarks":""},{"id":"gCAmount5","value":0,"remarks":""},{"id":"ammoniaAmount5","value":0,"remarks":""},{"id":"sulfuricAcidAmount5","value":0,"remarks":""},{"id":"fluorineAmount5","value":0,"remarks":""},{"id":"fluorsparTransportAmount5","value":0,"remarks":""},{"id":"naturalGasAmount5","value":0,"remarks":""},{"id":"electricityAmount5","value":0,"remarks":""},{"id":"processWaterAmount5","value":0,"remarks":""},{"id":"coolingWaterAmount5","value":0,"remarks":""},{"id":"labourcostAmount6","value":0,"remarks":""},{"id":"operatorsAmount6","value":0,"remarks":""},{"id":"incentiveAmount4","value":0,"remarks":""},{"id":"incentiveAmount5","value":0,"remarks":""}]}